{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name }}
  labels:
    app: {{ template "rethinkdb-single.name" . }}
    chart: {{ template "rethinkdb-single.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "rethinkdb-single.name" . }}
      release: {{ .Release.Name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
#---
#
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: pv0001
#  labels:
#    app: {{ template "rethinkdb-single.name" . }}
#    chart: {{ template "rethinkdb-single.chart" . }}
#    release: {{ .Release.Name }}
#    heritage: {{ .Release.Service }}
#spec:
#  capacity:
#    storage: {{ .Values.persistence.size | quote }}
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/data/db001"
