# Default values for veidemann-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-controller
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 50051

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: "linkerd"
    # kubernetes.io/tls-acme: "true"
  path: /veidemann.\api\.(Controller|Report.Status).*
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Trust a certificate by providing a ca cert as a secret
tls: {}
# secretName:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

config:
  # hostAliases
  issuer: ""
  db:
    host: rethinkdb-proxy
    port: 28015
    secretName: rethinkdb
  jaeger:
    agent:
      host: $(NODE_NAME)
      port: 5775
    sampler:
      type: probabilistic
      param: 0.1
  frontier:
    host: $(NODE_NAME)
    port: 4340
