kind: Job
apiVersion: batch/v1
metadata:
  name: {{ template "namerd.fullname" . }}-job
  labels:
    app: {{ template "namerd.name" . }}
    chart: {{ template "namerd.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: {{ template "namerd.fullname" . }}
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: namerctl-script
          configMap:
            name: {{ template "namerd.fullname" . }}-namerctl-script
            defaultMode: 0755
      containers:
        - name: {{ .Chart.Name }}-namerctl
          image: "{{ .Values.namerctl.image.repository }}:{{ .Values.namerctl.image.tag }}"
          imagePullPolicy: {{ .Values.namerctl.image.pullPolicy }}
          env:
            - name: NAMERCTL_BASE_URL
              value: "http://{{ template "namerd.fullname" . }}.default.svc.cluster.local:{{ .Values.service.apiPort }}"
          command:
            - "/namerctl/createNs.sh"
          volumeMounts:
            - name: "namerctl-script"
              mountPath: "/namerctl"
              readOnly: true
