---
apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: batch/v1
kind: Job
metadata:
  name: initdb
  namespace: db
spec:
  template:
    metadata:
      name: initdb
    spec:
      containers:
      - name: initdb
        image: norsknettarkiv/broprox-db-initializer:1.0.0-SNAPSHOT
        env:
        - name: DB_HOST
          value: "rethink.db"
        - name: DB_PORT
          value: "28015"
      restartPolicy: Never
