# Default values for namerd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

service:
  type: ClusterIP
  meshPort: &meshPort 4321
  syncPort: &syncPort 4100
  apiPort: &apiPort 4180
  adminPort: &adminPort 9991

image:
  repository: buoyantio/namerd
  tag: 1.3.5
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

kubectl:
  image:
    repository: buoyantio/kubectl
    tag: v1.8.5
    pullPolicy: IfNotPresent
  resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

namerctl:
  image:
    repository: linkerd/namerctl
    tag: 0.8.6
    pullPolicy: IfNotPresent
  resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# namerd configuration. The default configuration is located inside the ConfigMap.
# Allows to override the namerd configuration
config:
  admin:
    ip: 0.0.0.0
    port: *adminPort
  storage:
    kind: io.l5d.k8s
  namers:
    - kind: io.l5d.k8s
  interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: *syncPort
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: *meshPort
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: *apiPort

# script to create initial namerd dtabs
createNamespace: |-
  #!/bin/bash
  set -e
  namerctl dtab list
