apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "veidemann-frontier.fullname" . }}
  labels:
    app: veidemann
    component: {{ template "veidemann-frontier.name" . }}
    chart: {{ template "veidemann-frontier.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "veidemann-frontier.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: {{ template "veidemann-frontier.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: workdir
          emptyDir: {}
        - name: log4j-config
          configMap:
            name: {{ .Release.Name }}-veidemann
            items:
              - key: log4j2.xml
                path: log4j2.xml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7700
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: {{ .Values.config.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.config.db.port | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.db.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.db.secretName }}
                  key: password
            - name: HARVESTER_HOST
              value: {{ .Values.config.harvester.host | quote }}
            - name: HARVESTER_PORT
              value: {{ .Values.config.harvester.port | quote }}
            - name: ROBOTS_EVALUATOR_HOST
              value: {{ .Values.config.robotsEvaluator.host | quote }}
            - name: ROBOTS_EVALUATOR_PORT
              value: {{ .Values.config.robotsEvaluator.port | quote }}
            - name: DNS_RESOLVER_HOST
              value: {{ .Values.config.dnsResolver.host | quote }}
            - name: DNS_RESOLVER_PORT
              value: {{ .Values.config.dnsResolver.port | quote }}
            - name: JAEGER_AGENT_HOST
              value: {{ .Values.config.jaeger.agent.host | quote }}
            - name: JAEGER_AGENT_PORT
              value: {{ .Values.config.jaeger.agent.port | quote }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ .Values.config.jaeger.sampler.type | quote }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ .Values.config.jaeger.sampler.param | quote }}
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - name: log4j-config
              mountPath: /veidemann/config/log4j2.xml
              subPath: log4j2.xml
          resources: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
