# Default values for veidemann-initdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: norsknettarkiv/veidemann-db-initializer
  tag: latest
  pullPolicy: Always
  restartPolicy: Never

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  db:
    host: rethinkdb-proxy
    port: 28015
    secretName: rethinkdb
